=== Daneteee/DAW/1r DAW/XML/UF1/llibreria.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="llibreria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="llibre" type="dadesLlibres"
                minOccurs="2" maxOccurs="5" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="dadesLlibres">
        <xs:sequence>
            <xs:group ref="dadesLlibre" />
            <xs:element name="any" type="xs:date" />
        </xs:sequence>
        <xs:attribute name="ID" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:group name="dadesLlibre">
        <xs:sequence>
            <xs:element name="titol" type="xs:string" />
            <xs:element name="autor" type="xs:string" />
        </xs:sequence>
    </xs:group>
</xs:schema>

=== Daneteee/DAW/1r DAW/XML/UF1/llibreria.xml
<?xml version="1.0" encoding="UTF-8"?>
<llibreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="llibreria.xsd">
    <llibre ID="4243">
        <titol>La ultima noche de Rose Daly</titol>
        <autor>Tana French</autor>
        <any>2011-11-01</any>
    </llibre>

    <llibre ID="9167">
        <titol>Fahrenheit 451</titol>
        <autor>Ray Bradbury</autor>
        <any>1953-03-19</any>
    </llibre>

    <llibre ID="8402">
        <titol>La Fundaci√≥n</titol>
        <autor>Antonio Buero</autor>
        <any>1974-01-15</any>
    </llibre>
</llibreria>
