<?xml version="1.0"?>

 <!DOCTYPE agenda [ 
     <!ELEMENT agenda (contacte)> 
     <!ELEMENT contacte (nom, cognom+, telefon, email, adreca, genere)> 
     <!ELEMENT nom (#PCDATA)> 
     <!ELEMENT cognom (#PCDATA)> 
     <!ELEMENT email (#PCDATA)> 
     <!ELEMENT adreca (#PCDATA)> 
     <!ELEMENT telefon (#PCDATA)>
     <!ELEMENT genere (home|dona)>
     <!ELEMENT home EMPTY>
     <!ELEMENT dona EMPTY>
     <!ATTLIST contacte tipus (personal|treball)  #REQUIRED>
     <!ATTLIST agenda id ID #REQUIRED>
     <!ATTLIST telefon pais CDATA #REQUIRED> 
]> 

<agenda id="Contactes">
    <contacte tipus="personal">
        <nom>Dan</nom>
        <cognom>Maldonado Peralvo</cognom>
        <telefon pais="Espana">6991740222</telefon>
        <email>dan.maldonado.2132@lacetania.cat</email>
        <adreca>Calle Ubuntu, 404</adreca>
        <genere><home/></genere>
    </contacte>
</agenda>
